# Generated by Django 3.0.3 on 2020-03-04 01:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamingAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('spots', models.IntegerField()),
                ('price', models.IntegerField()),
                ('four_k', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StreamingService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('logo_url', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserStreamingAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('streaming_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daves_netflix.StreamingAccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='streamingaccount',
            name='streaming_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daves_netflix.StreamingService'),
        ),
        migrations.AddField(
            model_name='streamingaccount',
            name='users',
            field=models.ManyToManyField(related_name='users', through='daves_netflix.UserStreamingAccount', to=settings.AUTH_USER_MODEL),
        ),
    ]
